Repository DSC-Galgotias/HacktoberFest-2022, pull requests merged in 2022-10, with the labels that each got.

#5 Added Sorting Algorithms
  C/BubbleSort.c
  C/InsertionSort.c
  C/SelectionSort.c
Labels: hacktoberfest-accepted

#9 notepad using python
  Python/Notepad/Images/Save:edit_ feature.png
  Python/Notepad/Images/Simple_notepad.png
  Python/Notepad/Notepad.py
Labels: hacktoberfest-accepted, hacktoberfest-2022

#13 Added Tower of Hanoi
  Adjacent_duplicates.java
  Java/Tower_Of_Hanoi.java
  Python/Adjacent_duplicates.py
Labels: hacktoberfest-accepted, hacktoberfest-2022

#10 Added array code ,By solving 1 question
  Kotlin/Array.kt
Labels: hacktoberfest-accepted, hacktoberfest-2022

#7 Added 2 C++ Programs: 1 Algo, 1 Interview Question
  C++/Minimum_Spanning_Tree.cpp
  C++/Rat_In_A_Maze.cpp
Labels: hacktoberfest-accepted, hacktoberfest-2022

#16 lottery using solidity
  Solidity/lottery/raffle.sol
Labels: hacktoberfest-accepted, hacktoberfest-2022

#17 speedometer
  Javascript/Speedometer/Images/dials img.jpeg
  Javascript/Speedometer/Speedometer.html
Labels: hacktoberfest-accepted, hacktoberfest-2022

#20 Profile_finder
  Javascript/Profile-finder/README.md
  Javascript/Profile-finder/build/asset-manifest.json
  Javascript/Profile-finder/build/favicon.ico
  Javascript/Profile-finder/build/index.html
  Javascript/Profile-finder/build/logo192.png
  Javascript/Profile-finder/build/logo512.png
  Javascript/Profile-finder/build/manifest.json
  Javascript/Profile-finder/build/robots.txt
  Javascript/Profile-finder/build/static/css/main.f678d671.css
  Javascript/Profile-finder/build/static/css/main.f678d671.css.map
  Javascript/Profile-finder/build/static/js/main.1e5fe868.js
  Javascript/Profile-finder/build/static/js/main.1e5fe868.js.LICENSE.txt
  Javascript/Profile-finder/build/static/js/main.1e5fe868.js.map
  Javascript/Profile-finder/build/static/media/burger-loader.358b827a6d860ccb0238.gif
  Javascript/Profile-finder/package-lock.json
  Javascript/Profile-finder/package.json
  Javascript/Profile-finder/public/favicon.ico
  Javascript/Profile-finder/public/index.html
  Javascript/Profile-finder/public/logo192.png
  Javascript/Profile-finder/public/logo512.png
  Javascript/Profile-finder/public/manifest.json
  Javascript/Profile-finder/public/robots.txt
  Javascript/Profile-finder/src/App.js
  Javascript/Profile-finder/src/Components/NotFound.js
  Javascript/Profile-finder/src/Components/Preloader.js
  Javascript/Profile-finder/src/Components/Search.js
  Javascript/Profile-finder/src/Components/about.js
  Javascript/Profile-finder/src/Components/footer.js
  Javascript/Profile-finder/src/Components/info.js
  Javascript/Profile-finder/src/Components/interests.js
  Javascript/Profile-finder/src/NotFound.scss
  Javascript/Profile-finder/src/Pages/InfoPage.js
  Javascript/Profile-finder/src/Pages/SearchPage.js
  Javascript/Profile-finder/src/Search.scss
  Javascript/Profile-finder/src/burger-loader.gif
  Javascript/Profile-finder/src/config/api.js
  Javascript/Profile-finder/src/images/info_image.webp
  Javascript/Profile-finder/src/index.html
  Javascript/Profile-finder/src/index.js
  Javascript/Profile-finder/src/style.css
Labels: hacktoberfest-accepted, hacktoberfest-2022

#21 responsive website added
  HTML-CSS/Food-ordering-website/images/boxbike.webp
  HTML-CSS/Food-ordering-website/images/bulkbox.jpeg
  HTML-CSS/Food-ordering-website/images/contact.webp
  HTML-CSS/Food-ordering-website/images/home.jpeg
  HTML-CSS/Food-ordering-website/images/logo.png
  HTML-CSS/Food-ordering-website/images/logo1.webp
  HTML-CSS/Food-ordering-website/images/logo2.jpeg
  HTML-CSS/Food-ordering-website/images/logo3.jpeg
  HTML-CSS/Food-ordering-website/images/logo4.webp
  HTML-CSS/Food-ordering-website/images/logo5.webp
  HTML-CSS/Food-ordering-website/images/pizzabox.webp
  HTML-CSS/Food-ordering-website/index.css
  HTML-CSS/Food-ordering-website/index.html
  HTML-CSS/Food-ordering-website/phone.css
Labels: hacktoberfest-accepted, hacktoberfest-2022

#22 removed corrupted file
  Python/Notepad/Images/Save:edit_ feature.png
Labels: enhancement

#24 Calculator added using python
  Python/Calculator/Calculator.py
  Python/Calculator/Images/Calculator.jpeg
Labels: hacktoberfest-accepted, hacktoberfest-2022

#18 Added TaxiBooking.py
  Python/TaxiBooking.py
Labels: hacktoberfest-accepted, hacktoberfest-2022

#27 added a dice game
  Javascript/Dice Game/Images/dice1.png
  Javascript/Dice Game/Images/dice2.png
  Javascript/Dice Game/Images/dice3.png
  Javascript/Dice Game/Images/dice4.png
  Javascript/Dice Game/Images/dice5.png
  Javascript/Dice Game/Images/dice6.png
  Javascript/Dice Game/index.html
  Javascript/Dice Game/script.js
  Javascript/Dice Game/style.css
Labels: hacktoberfest-accepted, hacktoberfest-2022

#28 added a javascript project to visualise algorithms
  Javascript/Sorting Algorithm Visualizer/index.html
  Javascript/Sorting Algorithm Visualizer/script.js
  Javascript/Sorting Algorithm Visualizer/style.css
Labels: hacktoberfest-accepted, hacktoberfest-2022

#30 Created Merge2BST
  Java/Merge2BST.java
Labels: hacktoberfest-accepted, hacktoberfest-2022
